name: Android CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build Android Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup JDK (Java 17 recommended for Gradle 8+)
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Step 3: Setup Gradle cache for faster builds
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Step 4: Grant permission to Gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 5: Build project (Debug mode)
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Step 6 (optional): Run unit tests
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      # Step 7: Upload APK artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk